export interface Chatter {
	id?: number,
	twitch_name?: string,
	display_name?: string,
	color?: string,
	twitch_id?: number | string,
	twitch_channel?: string,
	channel_id?: number | string,
	moderator?: number,
	last_message?: number,
	last_command?: number,
	last_gamble?: number,
	points?: number,
	total_lost?: number,
	total_won?: number,
	gamble_wins?: number,
	gamble_losses?: number,
	exp?: number,
	level?: number,
	actual_message?: string,
	duel_wins?: number,
	duel_losses?: number,
	win_or_loss?: number,
	gambling_streak?: number,
	gambling_w_or_l?: number,
	duel_streak?: number,
	duel_w_or_l?: number,
	point_gain_time?: number,
	exp_gain_time?: number,
}

export const ChatterTable = 'chatters';